### ISSUE TITLE
question regarding example proceedings

### ISSUE THREAD

**Issue by ramsestom** [CianCoders/feathers-example-fileupload#1]
I have a question concerning the example. I am new to feathersjs so it is probably something I misunderstood, but in the example, the function that take a file to turn it into a datauri for blobservice is called inside a BEFORE hook. I thought before hooks where called before the service, to witch it applies, run. So how can this before hook handle the file created by multer from multipart data (with the function call:  multipartMiddleware.single('uri')) if this part of the code have not been executed yet? 
Or is it than in the case of multiple middelware functions called into the app.use() function, the before hooks would be inserted between the second to last and the last function? (I thought it would be called before any middelware function called by app.use() )

And couldn't we do something like:

```
app.use('/uploads',
    blobService({Model: blobStorage})
);

app.service('/uploads').before({
    create: [
        function(hook) {
            if (!hook.data.uri){
                 multipartMiddleware.single('uri'),  //don't know how to call multer here has I don't know if hooks have access to req, res and next.
                 if ( req.file)
                 {
                    const file = req.file;
                    const uri = dauria.getBase64DataURI(file.buffer, file.mimetype);
                    hook.data = {uri: uri};
                 }
            }
        }
    ]
});
```

which should be proper as multer needs to be called only in the 'create' function of the service and not in the 'get' one for example

**Comment by DenJohX** [comment]
You can see services as express middlewares, with hooks inside them, and preceded by any other middleware.

The syntax is 
`app.use('/endpoint', any, other, middleware, ..., thenTheActualService)`

So, yes, the multer middleware executes first, then a custom middleware to get the file data into feathers, and then the service (with its corresponding hooks).

About the hooks, you are right, there is no way to access `req` and `res` from inside a hook, because hooks are not middlewares, they are called by the actual middleware (the feathers service).

**Comment by ramsestom** [comment]
OK. So the running sequence would be 
any
other
middleware
before hooks
thenTheActualService
after hooks

Am I right?

**Comment by DenJohX** [comment]
It would be 
- any
- other
- middleware
- thenTheActualService
  - before hooks
  - service method (get, find, etc) 
  - after hooks
